#+TITLE:  Landau Theory for the Mott Transition in the Dimer lattice
#+AUTHOR: Óscar Nájera
#+EMAIL:  najera.oscar@gmail.com
#+DATE:   2016 Sep 13
#+TAGS:
#+LATEX_HEADER: \usepackage[top=2cm,bottom=2.5cm,left=3cm,right=3cm]{geometry}
#+LATEX_HEADER: \usepackage{indentfirst}
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+STARTUP: hideblocks
#+OPTIONS: toc:nil num:nil

* Above the critical point
# done in [[file:plot_docc_transition.py][file:~/dev/dmft-learn/examples/RKKY/plot_docc_transition.py]]
Starting from the reference cite:Kotliar2000 I try to do a fit on the
observable of the double occupation from the IPT data for the dimer
lattice above the critical point. Results are presented in figure
ref:fig:dimer_doc.

#+caption: Double occupation around the Metal-Insulator transition above the Critical point. Inflection point as marked with blue dots, and the dotted lines represent the derivatives normalized to fit in the same plot. label:fig:dimer_doc
[[./dimer_tp0.3_docc.pdf]]

Following cite:Kotliar2000 the system shall follow around the
transition point the shape of a Landau theory given by:

\begin{equation}
\label{eq:landau_theory}
p\eta + c\eta^3 = h
\end{equation}

where $\eta$ is the order parameter and $p,h$ are functions that
depend on the setup of the system $(T,U)$ and $c$ is a constant
describing the critical behavior.

In this first iteration of this study the I'll link the order
parameter to the observable of the double occupation by a
proportionality constant and express it in terms of a reduced
quantity, that means

\begin{equation}
\label{eq:eta_docc}
\eta \propto \langle d\rangle - d_c
\end{equation}

where $\langle d\rangle$ is the double occupation observable and $d_c$
is the double occupation at the inflection point of the double
occupation curves marked by the blue dots in figure
ref:fig:dimer_doc. This linear relation is certainly abusive as the
double occupation does not have a symmetrical behavior around the
$d_c$ point, but for this first study I'll keep it as such.

To perform the fit to the theory I use the new function:

\begin{equation}
\label{eq:fit_landau}
U-U_c=\frac{p\eta + c\eta^3}{1+q\eta}
\end{equation}

Where $U-U_c$ is the reduced interaction and is given by the data, and
$p,c,q$ are just just fitting constants. Results of this are presented
in figure ref:fig:dimer_fit_landau. The fit is quite acceptable, the
asymmetric behavior is more noticeable around the critical point and
makes the fit less good.

#+caption: Fit of the reduced double occupation to equation eqref:eq:fit_landau. Thick lines are the original data, thin lines the fit and black crosses the places where the fit can be enforced label:fig:dimer_fit_landau
[[./dimer_tp0.3_eta_landau.pdf]]

* Below the critical point
The plot in figure ref:fig:dimer_tp0.3_docc_bTc show the complete
asymmetry between the insulating and metallic branch. Insulator has a
quite flat behavior.

#+caption: Double occupation in the coexistence region. Clear evidence of the insulating side growing faster as temperature is lowered. label:fig:dimer_tp0.3_docc_bTc
[[./dimer_tp0.3_docc_bTc.pdf]]

Performing the fit to the landau theory is more complicated in this
branch when 2 solutions exist. A lot of care has to be put into
account when translating the system to the reduced quantities like
$\eta$ defined in equation eqref:eq:eta_docc and for numerical reason
in the search for a good fit I must set $q=0$ in equation
eqref:eq:fit_landau while performing the search.

Figure ref:fig:dimer_landau_bTc includes the resulting fit. There are
a few points to bring to attention. When one has only to fit a
specific branch the regime in which the fit is valid is much larger in
comparison to the previous section where the theory tries to describe
the behavior around the transition point. Here the behavior is more
benign. Nevertheless just at the edge of the transition the quality of
the fit decreases. The second observation is that the fit to the
metallic part is notably worse as it can not sustain a correct
behavior throughout the coexistence region as the insulator fit does.

#+caption: Fit of the order parameter to a Landau theory in the $T<T_c$ regime. Thick lines are the original data, thin lines the fit, and black crosses the places where the fit can be enforced. label:fig:dimer_landau_bTc
[[./dimer_tp0.3_eta_landau_bTc.pdf]]

bibliographystyle:unsrt
bibliography:~/Documents/library.bib,~/Documents/zotero.bib
